
services:
  api:
    build: .
    container_name: springboot_billing_api
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      # URL apuntando al puerto 6543 con prepareThreshold=0 para compatibilidad con Transaction Mode
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      
      # El usuario DEBE incluir el Project Reference de tu proyecto de Supabase
      SPRING_DATASOURCE_USERNAME: postgres.bntpezpmucyhyaooftgf
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      
      # Evita que Hibernate intente validar o extraer esquemas incompatibles con el Pooler
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"

      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      SENDGRID_TO_EMAIL: ${SENDGRID_TO_EMAIL}