spring.application.name=billing
server.port=8081
# Configuración de Conexión a la BD
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.bntpezpmucyhyaooftgf.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.mobile.billing=DEBUG
# Cambia esto a false para limpiar la consola
spring.jpa.show-sql=false


sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=${MAIL_FROM_ADDRESS:noreply@example.com}

# Límite de tamaño para subir archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB