name: Deploy API to Google Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: mi-billing-api-2026
  REGION: us-central1
  REPOSITORY: billing-repo
  SERVICE_NAME: billing-api
  IMAGE_URL: us-central1-docker.pkg.dev/mi-billing-api-2026/billing-repo/billing-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar con Maven
        run: mvn clean package -DskipTests

      - name: Autenticación en Google Cloud vía WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Autenticar Docker con Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Construir y subir imagen Docker
        run: |
          docker build -t ${{ env.IMAGE_URL }}:${{ github.sha }} -t ${{ env.IMAGE_URL }}:latest .
          docker push ${{ env.IMAGE_URL }}:${{ github.sha }}
          docker push ${{ env.IMAGE_URL }}:latest

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_URL }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --min-instances=0 \
            --set-env-vars SPRING_DATASOURCE_URL="${{ secrets.SUPABASE_URL }}",SPRING_DATASOURCE_USERNAME="postgres",SPRING_DATASOURCE_PASSWORD="${{ secrets.SUPABASE_PASS }}",SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}",MAIL_FROM_ADDRESS="${{ secrets.MAIL_FROM_ADDRESS }}"